### ISSUE TITLE
contextualConsentOnly on services not working as expected

### ISSUE THREAD

**Issue by klfman** [kiprotect/klaro#440]
**Klaro Config**

```yaml
      services:
        youtube:
          title: Youtube
          description: Youtube
          contextualConsentOnly: true
```

**Current behavior**

When having only one service, e.g. youtube, the cookie consent popups are displayed anyways, showing a switch for exactly that service.

**Expected behavior**

As there are only services with `contextualConsentOnly: true` the initial popup should never be displayed, because all consent can be given inline in a contextual consent in the web pages content.
